import { Universe, Galaxy, SolarSystem, Planet, CosmicPhenomena, QuizQuestion } from './types';

export const UNIVERSES: Universe[] = [
  {
    id: 'observable',
    name: 'Observable Universe',
    color: '#4488ff',
    age: '13.8 Billion Years',
    diameter: '93 Billion Light Years',
    galaxiesCount: '2 Trillion Galaxies',
    composition: 'H, He, C, O, Fe, Si',
    specialFeature: '100 Billion solar systems per galaxy. Liquid water stable zones.',
    description: 'Our home universe. Governed by Einsteinian Relativity and the Standard Model. Extremely flat in spatial curvature.',
    fact: 'Only about 5% of this universe consists of normal (baryonic) matter. The rest is dark matter and dark energy.'
  },
  {
    id: 'mirror',
    name: 'Mirror Universe',
    color: '#ff4488',
    age: '13.8 Billion Years',
    diameter: '93 Billion Light Years',
    galaxiesCount: '2 Trillion Galaxies',
    composition: 'Anti-Hydrogen, Anti-Helium, CPT-Reversed',
    specialFeature: 'Antimatter twin. Time runs structurally parallel but reversed in charge asymmetry.',
    description: 'A theoretical antimatter universe where charge, parity, and time (CPT) are perfectly symmetrical to our own. It would annihilate instantly on contact with our universe.',
    fact: 'Every particle in the mirror universe has the opposite charge of its partner in the observable universe.'
  },
  {
    id: 'dark',
    name: 'Dark Universe',
    color: '#4422aa',
    age: '15.2 Billion Years',
    diameter: '120 Billion Light Years',
    galaxiesCount: '500 Billion Remnants',
    composition: 'Weakly Interacting Massive Particles (WIMPs), Axions',
    specialFeature: 'No electromagnetic radiation. Governed purely by dark gravity.',
    description: 'A universe where the balance of primordial fluctuation collapsed normal baryonic matter entirely. 95% of its contents is dark matter and dark energy, with no nuclear light.',
    fact: 'Planetary structures here consist of crystalline dark-state sheets, invisible to conventional telescope lenses.'
  },
  {
    id: 'high-entropy',
    name: 'High-Entropy Universe',
    color: '#aa8844',
    age: '100 Trillion Years',
    diameter: '500 Billion Light Years',
    galaxiesCount: '0 (All merged into Black Holes)',
    composition: 'Hawking Radiation, Iron Core Planetesimals',
    specialFeature: 'Heat death state. Stars have all burned out or dissolved.',
    description: 'An ancient universe approaching absolute thermodynamic equilibrium. Heavy elements have decayed, and the skies are pitch black except for the glowing accretion clouds of fading black holes.',
    fact: 'Planetary surfaces here are frozen, inert blocks of iron, slowly evaporating through sub-atomic decay.'
  },
  {
    id: 'quantum-foam',
    name: 'Quantum Foam Universe',
    color: '#44aa88',
    age: 'N/A (Non-Linear Time)',
    diameter: 'Planck-Scale Infinite',
    galaxiesCount: 'Probabilistic Bubbles',
    composition: 'Quantum Loops, Virtual Particles',
    specialFeature: 'Planck-scale spacetime turbulence. Physics constantly collapses and re-forms.',
    description: 'A universe consisting entirely of sub-atomic foam, where dimensions fluctuate. Geometries are non-Euclidean, and time exists as a superposition of probable paths.',
    fact: 'In this universe, particles can exist in multiple places simultaneously, and causation is structurally bi-directional.'
  },
  {
    id: 'inflation',
    name: 'Inflation Universe',
    color: '#88aaff',
    age: '13.8 Billion Years',
    diameter: '10^100 Light Years',
    galaxiesCount: '10^80 Galaxies (Infinite Horizon)',
    composition: 'Primordial Hydrogen + Helium',
    specialFeature: 'Hyper-inflated 10^-32 seconds in. Mostly beyond the visual horizon forever.',
    description: 'An variant universe where the scalar inflaton field did not decay as quickly as ours, triggering an exponential expansion that created a mega-void of space containing isolated galaxy bubbles.',
    fact: 'This universe holds pockets of space that are expanding faster than the speed of light, sealing galactic zones forever.'
  },
  {
    id: 'string-theory',
    name: 'String Theory Universe',
    color: '#ff8844',
    age: '14.0 Billion Years',
    diameter: '100 Billion Light Years',
    galaxiesCount: '1.8 Trillion Galaxies',
    composition: '11-Dimensional Superstrings',
    specialFeature: '7 compactified extra dimensions at the Planck length. Vibrating string nodes.',
    description: 'A universe where standard point particles are explicitly understood as vibrating 1D strings in an 11-dimensional membrane, allowing direct interaction with gravity waves.',
    fact: 'Gravity in this universe does not decay by the square of distance, but by higher dimensional power structures.'
  },
  {
    id: 'brane',
    name: 'Brane Universe',
    color: '#cc44ff',
    age: '13.8 Billion Years',
    diameter: '93 Billion Light Years',
    galaxiesCount: '2 Trillion Galaxies',
    composition: 'Standard baryonic, gravity leaks to bulk',
    specialFeature: '3D membrane floating in a 5D bulk space. Collisions generate big bangs.',
    description: 'A universe that exists as a spatial slice or "membrane" floating through a higher-dimensional bulk. Gravity is uniquely free to leak out of the membrane, explaining why it is so weak.',
    fact: 'The initial cosmic explosion was not a singularity expanding, but the clash of two adjacent dimensional branes.'
  },
  {
    id: 'cyclic',
    name: 'Cyclic Universe',
    color: '#44ffcc',
    age: 'Infinite (Current Cycle: 10B yr)',
    diameter: 'Variable (95B ly currently)',
    galaxiesCount: '1.5 Trillion Galaxies',
    composition: 'Recycled Stellar Mediums',
    specialFeature: 'Eternal bounce. Cycle of expansion, contraction, crunch, and rebirth.',
    description: 'A cosmologically oscillating universe without an initial beginning or an end. It undergoes expansion, reverses under gravitational contraction into a Big Crunch, then rebounds.',
    fact: 'Black holes from prior cycles leave subtle thermal imprints on the modern cosmic microwave background.'
  },
  {
    id: 'holographic',
    name: 'Holographic Universe',
    color: '#ffcc44',
    age: '13.8 Billion Years',
    diameter: '93 Billion Light Years',
    galaxiesCount: '2 Trillion Galaxies',
    composition: 'Surface Boundary Fields',
    specialFeature: '3D reality projected from 2D boundary surface. Information bounds the horizon.',
    description: 'A universe where the three-dimensional volume we perceive is mathematically equivalent to quantum information inscribed on a distant, two-dimensional boundary.',
    fact: 'All physical processes in this universe can be computed as flat equations on the outer cosmic horizon.'
  },
  {
    id: 'alien-physics',
    name: 'Alien Physics Universe',
    color: '#ff44aa',
    age: '16.5 Billion Years',
    diameter: '100B Light Years',
    galaxiesCount: '1 Trillion Exotic Galaxies',
    composition: 'Plasmatic Crystalline, Strange Matter',
    specialFeature: 'Gravity is 10 times stronger. Constants allow organic silicon bindings.',
    description: 'A cosmos where the fine-structure constant and gravitational weights differ. Stars burn extremely short and hot, and chemistry is dominated by exotic silicon crystallization.',
    fact: 'Because of intense gravity, planets are much flatter, and life forms resemble low-lying bioluminescent sheets.'
  },
  {
    id: 'dark-energy-dominant',
    name: 'Dark Energy Dominant',
    color: '#aa44ff',
    age: '20.0 Billion Years',
    diameter: '900 Billion Light Years',
    galaxiesCount: '100 Galaxies (Widely Segregated)',
    composition: 'Fading atoms, 99.9% Quantum Vacuum',
    specialFeature: 'Dark energy is 99%. Acceleration will trigger the Big Rip in 20B years.',
    description: 'A universe undergoing rapid exponential expansion. Space is stretching so violently that galaxies are pushed out of each other’s visual horizons, leaving almost pure void.',
    fact: 'Eventually, even stars, planets, and atomic bonds will be torn apart by the accelerating space field.'
  },
  {
    id: 'crystalline',
    name: 'Crystalline Universe',
    color: '#44aaff',
    age: '13.8 Billion Years',
    diameter: '80 Billion Light Years',
    galaxiesCount: '3 Trillion Geometric Galaxies',
    composition: 'Lattice Matter, Quantum Coherent Nodes',
    specialFeature: 'Cosmic crystal lattice. Space is organized into hexagonal grid lanes.',
    description: 'A highly ordered universe where gravity waves cooled into a crystalline lattice at galactic scales. Stars are locked in precise geometric arrays, and dark matter behaves symmetrically.',
    fact: 'This universe exhibits perfect quantum coherence, allowing instant energy transfer across entire solar systems.'
  },
  {
    id: 'plasma',
    name: 'Plasma Universe',
    color: '#ff6644',
    age: '14.5 Billion Years',
    diameter: '95 Billion Light Years',
    galaxiesCount: '2 Trillion Filament Galaxies',
    composition: 'Charged Plasmas, Birkeland Currents',
    specialFeature: 'Electromagnetism is dominant over gravity. Spacetime has no dark matter.',
    description: 'An alternative cosmic model where colossal Birkeland electromagnetic currents shape galaxies out of dust. Light and plasma pinch effects generate stars instead of gravitational collapse.',
    fact: 'Vast electric webs span light-years, connecting planets together with glowing plasma bridges.'
  },
  {
    id: 'void',
    name: 'Void Universe',
    color: '#222244',
    age: '30.0 Billion Years',
    diameter: '500 Billion Light Years',
    galaxiesCount: '3 Galaxies Total',
    composition: 'Sparse Hydrogen Gas, Hawking Radiation',
    specialFeature: '99.9999% absolute vacuum. Space is nearly empty.',
    description: 'A barren universe with almost zero density. Formed without primordial density ripples, it contains only three isolated galaxies drifting in an infinite, pitch-black frozen expansion.',
    fact: 'Time runs sluggishly in terms of stellar activity, and temperatures rest at a fraction of a Kelvin above absolute zero.'
  }
];

export const GALAXIES: Galaxy[] = [
  {
    id: 'milkyway',
    name: 'Milky Way',
    type: 'Barred Spiral',
    diameter: '100,000 Light Years',
    starsCount: '200–400 Billion Stars',
    supermassiveBlackHole: 'Sagittarius A* (4 Million Solar Masses)',
    description: 'Our home galaxy featuring spectacular spiral arms wrapped around a central bar. The Solar System resides in the minor Orion Arm, roughly 26,000 light-years from the core.',
    fact: 'The Milky Way is currently moving at 110 kilometers per second toward its neighbor, Andromeda.',
    color: '#4ab8ff'
  },
  {
    id: 'andromeda',
    name: 'Andromeda (M31)',
    type: 'Spiral',
    diameter: '220,000 Light Years',
    starsCount: '1 Trillion Stars',
    supermassiveBlackHole: 'M31 Core SMBH (110 Million Solar Masses)',
    description: 'The largest galaxy in our Local Group. It is a majestic, tightly wound spiral that exhibits a dense nucleus hosting billions of ancient stars and a highly volatile black hole.',
    fact: 'In 4.5 billion years, Andromeda and the Milky Way will merge, forming a new elliptical galaxy nicknamed "Milkdromeda".',
    color: '#ff4488'
  },
  {
    id: 'triangulum',
    name: 'Triangulum (M33)',
    type: 'Spiral',
    diameter: '60,000 Light Years',
    starsCount: '40 Billion Stars',
    supermassiveBlackHole: 'No Confirmed Supermassive Black Hole',
    description: 'A beautifully structured face-on spiral galaxy. It is the third-largest member of the Local Group and is likely a gravitational satellite of the much larger Andromeda Galaxy.',
    fact: 'M33 showcases an extraordinarily high rate of star formation, containing some of the largest stellar nurseries in our cosmic neighborhood.',
    color: '#30e8c0'
  },
  {
    id: 'lmc',
    name: 'Large Magellanic Cloud',
    type: 'Irregular Dwarf',
    diameter: '14,000 Light Years',
    starsCount: '10 Billion Stars',
    supermassiveBlackHole: 'Intermediate-Mass BHs detected',
    description: 'A satellite dwarf galaxy of the Milky Way. Disrupted by galactic gravity, it lacks a defined shape but boasts spectacular gas clouds including the hyper-active 30 Doradus (Tarantula Nebula).',
    fact: 'Because of its proximity, it is one of the best laboratories for studying the life cycle of massive stars and supernova remnants.',
    color: '#e8b84b'
  },
  {
    id: 'centaurusa',
    name: 'Centaurus A (NGC 5128)',
    type: 'Lenticular',
    diameter: '97,000 Light Years',
    starsCount: '1 Trillion Stars',
    supermassiveBlackHole: 'Centaurus A SMBH (55 Million Solar Masses)',
    description: 'Our closest active radio galaxy, famous for its thick dust lane wrapping around its center and its intense relativisitic jets shooting matter thousands of light-years into space.',
    fact: 'The galaxy’s violent active nucleus is powered by a supermassive black hole consuming immense gaseous clouds.',
    color: '#ff8844'
  },
  {
    id: 'whirlpool',
    name: 'Whirlpool (M51)',
    type: 'Grand Design Spiral',
    diameter: '76,000 Light Years',
    starsCount: '200 Billion Stars',
    supermassiveBlackHole: 'M51 Core SMBH (1 Million Solar Masses)',
    description: 'A textbook spiral galaxy with prominent, dust-rich spiral arms and active starburst zones. It is gravitationally interacting with a smaller dwarf companion, NGC 5195, at its tip.',
    fact: 'The gravitational interaction with its companion triggers shockwaves, compresssing gas clouds to spawn new stars.',
    color: '#b070ff'
  },
  {
    id: 'sombrero',
    name: 'Sombrero (M104)',
    type: 'Spiral / Elliptical Hybrid',
    diameter: '50,000 Light Years',
    starsCount: '800 Billion Stars',
    supermassiveBlackHole: 'Sombrero SMBH (1 Billion Solar Masses)',
    description: 'Named for its striking resemblance to a Mexican hat, featuring a large, brilliant central bulge of ancient stars encircled by a thick, dark ring of cosmic dust.',
    fact: 'It contains an extremely rich population of globular clusters, estimated to count near 2,000.',
    color: '#ffcc44'
  },
  {
    id: 'm87',
    name: 'Messier 87 (M87)',
    type: 'Elliptical Giant',
    diameter: '980,000 Light Years',
    starsCount: '2 Trillion Stars',
    supermassiveBlackHole: 'M87* (6.5 Billion Solar Masses — Photographed!)',
    description: 'A supergiant elliptical galaxy in the Virgo Cluster. M87 is home to thousands of star clusters and is famous for a stellar relativistic jet venting plasma from its central leviathan black hole.',
    fact: 'In 2019, M87* became the historical first-ever black hole to be directly imaged by the Event Horizon Telescope.',
    color: '#ff4433'
  },
  {
    id: 'cartwheel',
    name: 'Cartwheel Galaxy',
    type: 'Ring Galaxy',
    diameter: '150,000 Light Years',
    starsCount: '150 Billion Stars',
    supermassiveBlackHole: 'Multiple Ultraluminous X-Ray Sources',
    description: 'Formed from a spectacular high-speed collision with an adjacent dwarf galaxy. A massive cosmic ripple expands outward from the collision point, compressing gas and creating a giant circle of newborn stars.',
    fact: 'The outer ring consists of immense starburst nurseries populated by short-lived, hyper-luminous blue giant stars.',
    color: '#30e8c0'
  },
  {
    id: 'ngc1300',
    name: 'NGC 1300',
    type: 'Barred Spiral',
    diameter: '110,000 Light Years',
    starsCount: '300 Billion Stars',
    supermassiveBlackHole: 'NGC 1300 Core (73 Million Solar Masses)',
    description: 'Described as a perfect barred spiral. The core exhibits a unique spiral structure inside the central bar, demonstrating the complex orbital mechanics of galactic dust.',
    fact: 'The blue dots across its spiraling arms represent clusters of young, hot stars heating surrounding hydrogen fields.',
    color: '#ffff66'
  },
  {
    id: 'sculptor',
    name: 'Sculptor (NGC 253)',
    type: 'Intermediate Spiral',
    diameter: '90,000 Light Years',
    starsCount: '150 Billion Stars',
    supermassiveBlackHole: 'NGC 253 Central BH (5 Million Solar Masses)',
    description: 'Known as the "Silver Coin" galaxy. It is a dusty starburst galaxy undergoing intense star formation, venting massive galactic winds of ionized gas into intergalactic space.',
    fact: 'It contains a super-cluster of massive stars at its nucleus, compressing dust clouds at thousands of times normal rates.',
    color: '#4ab8ff'
  },
  {
    id: 'blackeye',
    name: 'Black Eye Galaxy (M64)',
    type: 'Spiral',
    diameter: '50,000 Light Years',
    starsCount: '100 Billion Stars',
    supermassiveBlackHole: 'M64 Core (45 Million Solar Masses)',
    description: 'Known for its ominous profile, featuring a dark absorbing dust band sweeping across its glowing core. Believed to have absorbed a dwarf companion galaxy 1B years ago.',
    fact: 'The outer gas ring rotates in the opposite direction of the main inner star disk, creating high-shear turbulence.',
    color: '#ff44aa'
  }
];

export const SOLAR_SYSTEMS: SolarSystem[] = [
  {
    id: 'sol',
    name: 'Sol System',
    starType: 'G-type main-sequence star (Yellow Dwarf)',
    starTemp: '5,778 Kelvin',
    planetsCount: 8,
    age: '4.6 Billion Years',
    hasBlackHole: false,
    description: 'Our home planetary system. It features rocky inner worlds, a gas giant outer ring, and icy worlds in the Kuiper belt, orbiting a stable yellow star.'
  },
  {
    id: 'trappist1',
    name: 'TRAPPIST-1',
    starType: 'M-dwarf (Ultra-cool Red Dwarf)',
    starTemp: '2,566 Kelvin',
    planetsCount: 7,
    age: '7.6 Billion Years',
    hasBlackHole: false,
    description: 'An extraordinary compact planetary system with seven rocky Earth-sized worlds orbiting a dim red star. Three reside directly inside the habitable zone, holding potential liquid oceans.'
  },
  {
    id: 'kepler90',
    name: 'Kepler-90',
    starType: 'F-type main-sequence star',
    starTemp: '6,080 Kelvin',
    planetsCount: 8,
    age: '2.0 Billion Years',
    hasBlackHole: false,
    description: 'The first eight-planet exoplanetary system found beyond ours. Handfully analyzed using Google machine learning models to detect Kepler-90i, a sizzling super-Earth.'
  },
  {
    id: 'alphacentauri',
    name: 'Alpha Centauri',
    starType: 'Binary System (G2V + K1V) + M5V (Proxima)',
    starTemp: '5,790 / 5,260 / 3,000 Kelvin',
    planetsCount: 3,
    age: '5.3 Billion Years',
    hasBlackHole: false,
    description: 'Our closest stellar neighbors just 4.37 light-years away. Proxima Centauri b orbits its tiny red host in a habitable zone, targeted for future interstellar micro-probe missions.'
  },
  {
    id: 'psrb1257',
    name: 'PSR B1257+12',
    starType: 'Millisecond Pulsar (Neutron Star)',
    starTemp: '1,000,000+ Kelvin (Core Remnant)',
    planetsCount: 3,
    age: '8.0 Billion Years',
    hasBlackHole: false,
    description: 'A dead system. The central body is a rapidly spinning magnetizer pulsar. Famous for hosting the first verified exoplanets ever discovered in 1992, orbiting in lethal radiation fields.'
  },
  {
    id: 'gliese667',
    name: 'Gliese 667',
    starType: 'Triple Star System (M-dwarf dominant)',
    starTemp: '3,700 Kelvin',
    planetsCount: 6,
    age: '6.0 Billion Years',
    hasBlackHole: false,
    description: 'A stunning system containing three suns. Multiple super-Earths orbit Gliese 667C, with three worlds situated in habitable templates, offering gorgeous triple sunrises.'
  },
  {
    id: 'cygnusx1',
    name: 'Cygnus X-1',
    starType: 'Stellar-Mass Black Hole + Blue O-star companion',
    starTemp: '31,000 Kelvin (O-Star) / Accretion Disk extreme',
    planetsCount: 1,
    age: '5.0 Million Years',
    hasBlackHole: true,
    description: 'CYGNUS TIME DILATION SYSTEM. A blue supergiant is slowly stripped of its outer hydrogen layers, feeding a spinning 21-solar-mass stellar black hole. Highly volatile orbit speeds.',
    timeDilation: true
  },
  {
    id: 'm87core',
    name: 'M87 Core Leviathan',
    starType: 'Active accretion disk surrounding M87*',
    starTemp: 'Trillions of Kelvin equivalent core speed',
    planetsCount: 2,
    age: '12.0 Billion Years',
    hasBlackHole: true,
    description: 'EXTREME TIME DILATION DUAL-CLOCK SYSTEM. Orbiting the Event Horizon of the 6.5-Billion solar-mass black hole. Space and time distort so heavily that a single hour feels like months elsewhere.',
    timeDilation: true
  },
  {
    id: 'hr8799',
    name: 'HR 8799',
    starType: 'A-type main-sequence star',
    starTemp: '7,430 Kelvin',
    planetsCount: 4,
    age: '60 Million Years',
    hasBlackHole: false,
    description: 'A very young system famous for being the first multi-planet exoplanetary system to have its outer gas giants directly imaged, slowly orbiting in massive dust rings.'
  },
  {
    id: 'cancri55',
    name: '55 Cancri',
    starType: 'Binary System (Yellow G-Dwarf + Red M-Dwarf)',
    starTemp: '5,196 Kelvin',
    planetsCount: 5,
    age: '7.4 Billion Years',
    hasBlackHole: false,
    description: 'Hosts 55 Cancri e, an exotic tidally locked "carbon super-Earth". Its interior is so compressed it would be structured largely out of pristine crystalline diamond layers.'
  },
  {
    id: 'xeno1',
    name: 'XENO-1 System',
    starType: 'Fictional Alien Tricolored Star Group',
    starTemp: '4,100 Kelvin',
    planetsCount: 8,
    age: '6.5 Billion Years',
    hasBlackHole: true, // Nearby black hole warp effects
    description: 'BIOLUMINESCENT ALIEN REALM. System resting adjacent to a stable wormhole corridor. The worlds have evolved silicon-based and liquid methane ecosystems with heavy space curvature dilation.',
    timeDilation: true
  },
  {
    id: 'umbra7',
    name: 'UMBRA-7 Dark Gravity',
    starType: 'Theoretical Dark Star (Fossil)',
    starTemp: '2.7 Kelvin (Thermal Background)',
    planetsCount: 4,
    age: '13.5 Billion Years',
    hasBlackHole: false,
    description: 'A theoretical system bound strictly by a dark matter focal throat. The star emits no electromagnetic waves but exerts a massive, highly ordered gravity holding planetesimal bodies in lock.'
  }
];

export const PLANETS: Planet[] = [
  {
    id: 'sun',
    name: 'The Sun',
    type: 'G2V Dwarf Star',
    radius: 3.2,
    color: '#ffdd60',
    realDiameter: '1,392,700 km',
    tempRange: '5,778 K (Surface) / 15M K (Core)',
    moonsCount: 0,
    composition: '71% Hydrogen, 27% Helium, 2% Metals',
    specialFeature: 'Accounts for 99.86% of the solar system\'s total mass; produces light via nuclear fusion.',
    description: 'Our host star. Its massive gravitational pull keeps our entire solar system bound. Powered by core quantum fusion which slowly vents photons.',
    emissive: true,
    emissiveIntensity: 1.4,
    atmosphereColor: '#ff8800',
    animationType: 'pulsing'
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'Terrestrial Rocky Planet',
    radius: 0.8,
    color: '#b5b5b5',
    realDiameter: '4,879 km',
    tempRange: '-180°C to 430°C',
    moonsCount: 0,
    composition: '70% Iron Core, 30% Silicates',
    specialFeature: 'Strongest temperature swings in the solar system; iron core comprises 85% of its volume.',
    description: 'The closest planet to the Sun. Mercury is structurally a massive iron ball covered by a thin mantle of silicate crust, peppered with crater lines.',
    animationType: 'none'
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'Terrestrial Rocky Planet',
    radius: 1.1,
    color: '#e8cda0',
    realDiameter: '12,104 km',
    tempRange: '465°C constant',
    moonsCount: 0,
    composition: 'Carbon Dioxide (96.5%), Nitrogen (3.5%)',
    specialFeature: 'Runaway greenhouse effect; rotates backward (retrograde) extremely slowly.',
    description: 'Venus is Earth\'s sister size but exists as an absolute pressure furnace. Its yellow-cream clouds of sulfuric acid trap solar heat dynamically.',
    animationType: 'pulsing'
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'Terrestrial Rocky Planet',
    radius: 1.2,
    color: '#3a8fff',
    realDiameter: '12,742 km',
    tempRange: '-89°C to 58°C (Average 15°C)',
    moonsCount: 1,
    composition: '32% Iron, 30% Oxygen, 15% Silicon, 14% Magnesium',
    specialFeature: 'Only confirmed body to host abundant organic life; features liquid surface oceans.',
    description: 'Our home. A beautiful blue marble protected by active plate tectonics and a magnetosphere trapping water sheets and an nitrogen-oxygen blend.',
    atmosphereColor: '#4ab8ff',
    animationType: 'none'
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'Terrestrial Rocky Planet',
    radius: 0.9,
    color: '#c1440e',
    realDiameter: '6,779 km',
    tempRange: '-153°C to 20°C (Average -60°C)',
    moonsCount: 2,
    composition: 'Carbon Dioxide (95%), Iron Oxide crust',
    specialFeature: 'Olympus Mons (21.9km volcano); rich presence of surface water ice in polar layers.',
    description: 'The Red Planet, colored by iron-oxide rust. Cold and dry with a hyper-thin carbon dioxide atmosphere, currently mapped by robotic rovers.',
    animationType: 'none'
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'Gas Giant',
    radius: 2.8,
    color: '#c88b3a',
    realDiameter: '139,820 km',
    tempRange: '-108°C cloud tops',
    moonsCount: 95,
    composition: '89% Hydrogen, 10% Helium, trace Ammonia etc.',
    specialFeature: 'The Great Red Spot, a colossal storm wider than Earth running for 350+ years.',
    description: 'A vacuum cleaner of the solar system, Jupiter is a massive sphere of gas compressing hydrogen into a metallic superconducting state deep inside.',
    animationType: 'pulsing'
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'Gas Giant',
    radius: 2.4,
    color: '#e8d8a0',
    realDiameter: '116,460 km',
    tempRange: '-138°C average',
    moonsCount: 146,
    composition: '96% Hydrogen, 3% Helium, trace Methane',
    specialFeature: 'Vast, spectacular ring system made of billions of fragments of pure water ice and dust.',
    description: 'A gorgeous ringed planet with an extremely low density—Saturn could float in a massive cosmic bathtub. Rings span 282,000 km across.',
    hasRings: true,
    animationType: 'none'
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'Ice Giant',
    radius: 1.8,
    color: '#7de8e8',
    realDiameter: '50,724 km',
    tempRange: '-224°C (Coldest atmospheric body)',
    moonsCount: 27,
    composition: 'Hydrogen (83%), Helium (15%), Methane (2%)',
    specialFeature: 'Rotates on its side with a 98-degree axial tilt, likely from a colossal ancient impact.',
    description: 'A pale cyan ice giant with faint, vertical rings. Its deep interior consists of a pressurized, hot water-methane-ammonia liquid slush.',
    animationType: 'none'
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'Ice Giant',
    radius: 1.7,
    color: '#2244ff',
    realDiameter: '49,244 km',
    tempRange: '-201°C core average',
    moonsCount: 16,
    composition: '80% Hydrogen, 19% Helium, 1% Methane',
    specialFeature: 'Highest wind speeds in the solar system, peaking at an extreme 2,100 km/h.',
    description: 'A deep blue wind machine. Neptune is the most remote major planet, with an active atmosphere showing dark vortex storms like the Great Dark Spot.',
    animationType: 'none'
  },
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'Dwarf Planet',
    radius: 0.6,
    color: '#bbaa99',
    realDiameter: '2,377 km',
    tempRange: '-230°C typical',
    moonsCount: 5,
    composition: 'Nitrogen Ice shell, Rocky core base',
    specialFeature: 'Tombaugh Regio, a majestic heart-shaped glacier consisting of frozen nitrogen layers.',
    description: 'Reclassified as a dwarf planet in 2006. Pluto boasts an active structure of nitrogen glaciers, liquid ice volcanoes, and the massive orbiting moon Charon.',
    animationType: 'none'
  },
  {
    id: 'nexus1',
    name: 'Nexus-1 (Exotic)',
    type: 'Bioluminescent Silicon Planet',
    radius: 1.5,
    color: '#aa44ff',
    realDiameter: '18,500 km',
    tempRange: '-40°C to 80°C',
    moonsCount: 3,
    composition: 'Liquid Methane ocean, Silicon Lattice soil',
    specialFeature: 'Bioluminescent purple foliage structures and high levels of quantum grid crystallization.',
    description: 'A crystalline alien planet that is physically bound adjacent to a time warp pocket. Its atmosphere glows under cosmic particle excitation.',
    atmosphereColor: '#b070ff',
    animationType: 'alien'
  },
  {
    id: 'umbra',
    name: 'Dark Planet UMBRA',
    type: 'Theoretical Dark matter sphere',
    radius: 1.3,
    color: '#111133',
    realDiameter: '25,000 km',
    tempRange: '2.7 K (Fossilized Background)',
    moonsCount: 0,
    composition: 'Non-Baryonic Dark Matter (100%)',
    specialFeature: 'Zero electromagnetic light reflection. Completely invisible to standard sensory cameras.',
    description: 'A theoretical sphere of dense cold dark matter. It absorbs no photons, and is trackable strictly by its gravitational lensing of background stars.',
    animationType: 'flicker'
  }
];

export const COSMIC_PHENOMENA: CosmicPhenomena[] = [
  {
    id: 'blackholes',
    name: 'Black Holes',
    description: 'Region of spacetime where gravity is so strong that nothing, not even light, can escape.',
    stats: 'Density: Infinite Singularity | Spin: Kerr metric standard',
    fact: 'Tidal gravitational forces are so intense that an approaching traveler would undergo spaghettification, stretching into a subatomic string.',
    type: 'blackhole'
  },
  {
    id: 'wormholes',
    name: 'Wormholes',
    description: 'Theoretical topological passages or cosmic short-cuts connecting distant points in spacetime.',
    stats: 'Einstein-Rosen Metric | Required content: Negative-density exotic energy',
    fact: 'According to General Relativity, a stable traversable wormhole requires a thread of negative energy to hold its throat from collapsing.',
    type: 'wormhole'
  },
  {
    id: 'pulsars',
    name: 'Pulsars (Neutron Stars)',
    description: 'Highly magnetized, rapidly spinning neutron stars emitting fierce beams of electromagnetic radiation.',
    stats: 'RPM: Up to 43,000 | Mass: 1.4 Suns compressed into the size of a city',
    fact: 'A single teaspoon of a neutron star\'s ultra-dense degenerate matter would weigh more than Mount Everest.',
    type: 'pulsar'
  },
  {
    id: 'darkmatter',
    name: 'Dark Matter Web',
    description: 'The invisible structural scaffold of the universe, holding galaxies in position across cosmic voids.',
    stats: 'Density: 27% of total universe mass | Radiation interaction: 0',
    fact: 'The Cosmic Web refers to filaments of dark matter that guide the flow of normal gas to condense and form clusters.',
    type: 'darkmatter'
  },
  {
    id: 'inflation',
    name: 'Cosmic Inflation',
    description: 'The brief era of exponential, hyper-luminal expansion immediately following the singularity.',
    stats: 'Era: 10^-36 seconds | Linear Expansion rate: 10^26 fold increase',
    fact: 'Inflation flattened any spatial curvature, explaining why our portion of the universe appears so mathematically flat.',
    type: 'inflation'
  },
  {
    id: 'gravitationalwaves',
    name: 'Gravitational Waves',
    description: 'Ripples in the fabric of spacetime created by highly volatile collisions, like black hole mergers.',
    stats: 'First Detected: LIGO (2015) | Speed: Speed of Light',
    fact: 'When gravitational waves pass through you, they warp your length, stretching and compressing atomic space by fractions of a proton.',
    type: 'gravitationalwave'
  },
  {
    id: 'darkenergy',
    name: 'Dark Energy',
    description: 'The mysterious repulsive vacuum force driving the accelerating expansion of modern space.',
    stats: 'Cosmological Constant | Volume: 68% of modern universe constituent',
    fact: 'As space expands, dark energy does not dilute in density; it maintains a constant force, pushing the universe toward a Big Rip.',
    type: 'darkenergy'
  },
  {
    id: 'quantum',
    name: 'Quantum Entanglement',
    description: 'A phenomenon where sub-atomic states link instantly, crossing light-years without signal wires.',
    stats: 'State: Superposition | Principle: Action-At-A-Distance (Einstein)',
    fact: 'Entanglement allows quantum computation, but cannot be used to transmit messages faster than light due to absolute state chaos.',
    type: 'quantum'
  },
  {
    id: 'timedilation',
    name: 'Spacetime Time Dilation',
    description: 'An effect where time slows down in the vicinity of intense gravitational mass or ultra-high speed travel.',
    stats: 'Equations: Einstein’s Special and General Relativity',
    fact: 'A person standing near a supermassive black hole event horizon for a single hour would return to find centuries have passed on earth.',
    type: 'timedilation'
  },
  {
    id: 'spacetimecurvature',
    name: 'Spacetime Curvature',
    description: 'The geometric warping of the fabric of spacetime by mass and energy, creating gravity as described by Einstein.',
    stats: 'Relativistic Metric: g_μν | Fabric Grid Deformation',
    fact: 'Perform an experiment! Drag the experiment mass factor to watch the spacetime fabric warp, curving test trajectories in real-time.',
    type: 'spacetimecurvature'
  },
  {
    id: 'milestones',
    name: 'Space Travel Timeline',
    description: 'Historical milestones tracing humanity’s steps into the stars, from simple rockets to warp drive theory.',
    stats: 'Era: 1957 to 2060s Interstellar targets',
    fact: 'Voyager 1 was launched in 1977 and entered interstellar space in 2012, still venting weak radio coordinates back to NASA.',
    type: 'milestones'
  }
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  { id: 1, question: 'What is the closest star to Earth?', options: ['Alpha Centauri', 'Sirius', 'Proxima Centauri', 'Sol (The Sun)'], answerIndex: 3, explanation: 'Sol (The Sun) is our closest star. Beyond our solar system, Proxima Centauri is the nearest.', category: 'normal' },

  { id: 2, question: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], answerIndex: 1, explanation: 'There are exactly 8 official planets. Pluto was reclassified as a dwarf planet in 2006.', category: 'normal' },
  { id: 3, question: 'What is the largest planet in our solar system?', options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'], answerIndex: 2, explanation: 'Jupiter is the massive gas giant, hosting over twice the mass of all other planets combined.', category: 'normal' },
  { id: 4, question: 'What is a light year?', options: ['The time it takes light to orbit the Sun', 'The distance light travels in one year', 'The age of light since the Big Bang', 'The speed of light in deep vacuum space'], answerIndex: 1, explanation: 'A light-year is a unit of astronomical distance, measuring roughly 9.5 trillion kilometers.', category: 'normal' },
  { id: 5, question: 'What causes a black hole to form?', options: ['The collision of two hyper-massive planets', 'The thermodynamic cooling of a white dwarf star', 'The gravitational collapse of an extremely massive star core', 'The sudden expansion of dark matter filaments'], answerIndex: 2, explanation: 'When stars with massive cores run out of fuel, gravity wins, collapsing the core into a singularity.', category: 'normal' },
  { id: 6, question: 'What is dark matter?', options: ['Matter that has been swallowed by black holes', 'Invisible matter detectable strictly through gravitational effects', 'Dust sheets blocking light in interstellar clouds', 'Protons that have decayed into passive states'], answerIndex: 1, explanation: 'Dark matter does not interact with electromagnetic light, but is tracked because its gravity binds galaxies.', category: 'normal' },
  { id: 7, question: 'In what year did the first human step onto the Moon?', options: ['1961', '1965', '1969', '1972'], answerIndex: 2, explanation: 'Neil Armstrong stepped onto the Lunar surface on July 20, 1969, during the Apollo 11 mission.', category: 'normal' },
  { id: 8, question: 'What is the Milky Way?', options: ['The solar accretion disk surrounding the sun', 'Our home spiral galaxy', 'The local cluster of planets near Andromeda', 'The gas stream left by comets crossing Earth\'s orbit'], answerIndex: 1, explanation: 'The Milky Way is our barred spiral galaxy, holding about 100 billion solar systems.', category: 'normal' },
  { id: 9, question: 'What is time dilation?', options: ['The tendency of clocks to fail in solar storm lines', 'Earth spinning faster over historical eras', 'Time slowing down near massive gravity or at high speeds', 'An illusion of time based on coordinate distance'], answerIndex: 2, explanation: 'Time is relative. Clocks tick slower in strong gravitational fields and when traveling close to light-speed.', category: 'normal' },
  { id: 10, question: 'What was the first artificial satellite launched into orbit?', options: ['Sputnik 1', 'Explorer 1', 'Vanguard 1', 'Telstar'], answerIndex: 0, explanation: 'Sputnik 1 was launched by the Soviet Union on October 4, 1957, initiating the Space Age.', category: 'normal' },
  { id: 11, question: 'Which is the hottest planet in our solar system?', options: ['Mercury', 'Venus', 'Mars', 'Jupiter'], answerIndex: 1, explanation: 'Venus is the hottest because its thick carbon dioxide atmosphere traps intense solar heat.', category: 'normal' },
  { id: 12, question: 'What is a neutron star?', options: ['A star structured strictly out of hydrogen molecules', 'A hyper-compressed stellar core containing collapsed degenerate matter', 'A young planetesimal accumulation', 'A black hole accretion ring segment'], answerIndex: 1, explanation: 'Formed from supernovae, they hold up to 1.4-2 solar masses inside a city-sized radius.', category: 'normal' },
  { id: 13, question: 'What is the "event horizon" of a black hole?', options: ['The peak brightness region of the accretion disk', 'The furthest gravitational pull distance', 'The point of no return where escape speed exceeds light speed', 'The core point of infinite curvature densities'], answerIndex: 2, explanation: 'Beyond the event horizon, space-time paths curve inward so heavily that nothing can escape.', category: 'normal' },
  { id: 14, question: 'Which space telescope was successfully launched in 2021 as Hubble\'s successor?', options: ['Kepler Space Telescope', 'James Webb Space Telescope', 'Spitzer Telescope', 'Chandra Observatory'], answerIndex: 1, explanation: 'The James Webb Space Telescope (JWST) launched on Christmas Day 2021 to observe infrared light.', category: 'normal' },
  { id: 15, question: 'What is quantum entanglement?', options: ['Particles colliding inside stars to fuel fusion', 'Static interference on radio bands from cosmic webs', 'Instant state links between twin particles crossing distance', 'A method of compressing atoms into dark states'], answerIndex: 2, explanation: 'Entangled particles share states instantly, coined "spooky action at a distance" by Einstein.', category: 'normal' },
  { id: 16, question: 'What is the estimated age of our universe?', options: ['4.6 Billion Years', '10.2 Billion Years', '13.8 Billion Years', '20.0 Billion Years'], answerIndex: 2, explanation: 'Analyses of cosmic expansion and CMB radiation estimate the age to be 13.8 billion years.', category: 'normal' },
  { id: 17, question: 'What is a wormhole in physics?', options: ['A planetary tube created by high-speed asteroid tunnels', 'A theoretical tunnel crossing spacetime coordinates shortcut', 'A gaseous cloud connecting binary stellar systems', 'The spin axis of a rotating black hole core'], answerIndex: 1, explanation: 'Wormholes are theoretical mathematical tunnels allowed by relativity, bridging separate spacetime regions.', category: 'normal' },
  { id: 18, question: 'What is the name of the largest volcano in our solar system?', options: ['Mauna Kea (Earth)', 'Olympus Mons (Mars)', 'Mount Etna (Earth)', 'Loki Patera (Io)'], answerIndex: 1, explanation: 'Olympus Mons is a massive shield volcano on Mars, standing about 22 kilometers tall.', category: 'normal' },
  { id: 19, question: 'What is the Big Bang?', options: ['The collision of the Milky Way and Andromeda', 'The expanding source event of spacetime starting 13.8 billion years ago', 'The sound of a collapsing supergiant star supernova', 'A sudden wave of gamma rays from active cores'], answerIndex: 1, explanation: 'The Big Bang is the primordial expansion event that launched space, time, and matter.', category: 'normal' },
  { id: 20, question: 'What is Hawking radiation?', options: ['Lethal protons emitted by active pulsar beams', 'Slow mass evaporation from black holes due to quantum virtual particles', 'The background microwave light left by inflation', 'Charged solar wind streams shaping auroras'], answerIndex: 1, explanation: 'Proposed by Stephen Hawking, quantum particle pairs near the event horizon trigger gradual black hole decay.', category: 'normal' },
  { id: 21, question: 'In what year was Pluto reclassified as a dwarf planet?', options: ['2000', '2004', '2006', '2010'], answerIndex: 2, explanation: 'The International Astronomical Union redefined "planet" in 2006, placing Pluto as a dwarf.', category: 'normal' },
  { id: 22, question: 'What is the Oort Cloud?', options: ['The carbon ring surrounding Saturn\'s outer moon lines', 'A theoretical giant sphere of icy comets surrounding our solar system', 'The stellar dust lane inside the Milky Way center', 'A collection of black holes in the Virgo cluster'], answerIndex: 1, explanation: 'The Oort cloud is a colossal gravitational swarm of icy planetesimals, sourcing long-period comets.', category: 'normal' },
  { id: 23, question: 'What was the first human-built space station, launched in 1971?', options: ['Skylab', 'Salyut 1', 'Mir', 'International Space Station'], answerIndex: 1, explanation: 'Salyut 1 was orbiting under Soviet command in 1971, marking the start of long-term orbital habitation.', category: 'normal' },
  { id: 24, question: 'What is a pulsar?', options: ['A giant flashing star nearing carbon collapse', 'A rapidly spinning neutron star venting electromagnetic beams', 'A planetesimal reflecting solar flares intensely', 'An artificial probe generating grid signals'], answerIndex: 1, explanation: 'Pulsars are spinning magnetic neutron stars. Their beams swing across Earth like lighthouses.', category: 'normal' },
  { id: 25, question: 'What is cosmic inflation?', options: ['The accelerating price of space exploration rocket components', 'A theory of rapid, hyper-exponential expansion in the initial fraction of a second', 'Dust expanding into nebulae after stellar collapse', 'The dilution of dark energy in expanded space'], answerIndex: 1, explanation: 'Inflation expanded the cosmos by a massive scale factor in roughly 10^-32 seconds.', category: 'normal' },
  { id: 26, question: 'How many moons does Saturn currently have confirmed?', options: ['62', '82', '95', '146'], answerIndex: 1, explanation: 'Saturn leads with 146 confirmed moons, heavily mapped by robotic missions.', category: 'normal' },
  { id: 27, question: 'What is the speed of light in a vacuum?', options: ['150,000 km/s', '299,792 km/s', '450,000 km/s', '1,079,000 km/s'], answerIndex: 1, explanation: 'Light moves at roughly 300,000 kilometers per second, forming the cosmic speed limit.', category: 'normal' },
  { id: 28, question: 'How far away is the Andromeda Galaxy (M31) from us?', options: ['10,000 Light Years', '1.2 Million Light Years', '2.537 Million Light Years', '10.5 Million Light Years'], answerIndex: 2, explanation: 'Andromeda is around 2.5 million light-years away, detectable via high-end consumer optics.', category: 'normal' },
  { id: 29, question: 'What is dark energy?', options: ['Gravity fields leaking into bulk dimensions', 'The energy emitted by black hole singularities', 'A mysterious vacuum pressure accelerating the expansion of the universe', 'The potential thermal footprint of mirror universes'], answerIndex: 2, explanation: 'Dark energy is a smooth background pressure driving galaxies away from each other at increasing rates.', category: 'normal' },
  { id: 30, question: 'What was the name of the first robotic rover to arrive on Mars?', options: ['Sojourner', 'Spirit', 'Curiosity', 'Perseverance'], answerIndex: 0, explanation: 'Sojourner landed on July 4, 1997, as part of the Mars Pathfinder mission.', category: 'normal' },
  { id: 31, question: 'What is a magnetar?', options: ['A planet bound strictly by diamond-carbon lattices', 'A neutron star with an extremely powerful magnetic field', 'An iron asteroid generating stable magnetic fields', 'A space exploration probe seeking solar dust maps'], answerIndex: 1, explanation: 'Magnetars are neutron stars with magnetic field strengths trillions of times greater than Earth.', category: 'normal' },
  { id: 32, question: 'What does the Kardashev scale measure?', options: ['The gravity indices of extreme black holes', 'The sub-atomic vibration frequency of superstrings', 'A theoretical civilization\'s level of technological energy handling', 'The expansion velocity of parallel dimension clusters'], answerIndex: 2, explanation: 'Created by Nikolai Kardashev, it scores civilizations by planetary, stellar, and galactic energy use.', category: 'normal' },
  { id: 33, question: 'What is multiverse theory?', options: ['The belief that the Milky Way contains multiple smaller sun rings', 'A model hosting multiple bubble or parallel universes', 'The structure of dark matter filaments overlapping', 'The historical system of gravity working reversely'], answerIndex: 1, explanation: 'It suggests our observable space is just one of many distinct, potentially parallel universes.', category: 'normal' },
  { id: 34, question: 'What historical achievement did Voyager 1 record in 2012?', options: ['Orbiting Saturn\'s ring system for primary details', 'Landing a container on an interstellar comet', 'Becoming the first human object to enter interstellar space', 'Directly imaging the central SAGITTARIUS A* black hole'], answerIndex: 2, explanation: 'Voyager 1 crossed the heliopause in August 2012, venturing into interstellar coordinate spaces.', category: 'normal' },
  { id: 35, question: 'What is the Chandrasekhar limit?', options: ['The maximum speed of spacecraft in planetary systems', 'The maximum mass threshold of a stable white dwarf (1.4 solar masses)', 'The distance limits of gravitational lens focus', 'The minimum temperatures required for quantum atomic state pairings'], answerIndex: 1, explanation: 'Above 1.4 solar masses, electron degeneracy cannot balance gravity, collapsing white dwarfs.', category: 'normal' },
  { id: 36, question: 'What is gravitational lensing?', options: ['A technique to polish optical telescope mirror coatings', 'Gravity warping light beams around massive bodies like a lens', 'Dust scattering blue sunlight in atmospheric shields', 'Black holes radiating extreme energy paths outward'], answerIndex: 1, explanation: 'Mass curves spacetime. Photons traveling past massive targets bend, creating lens distortions.', category: 'normal' },
  { id: 37, question: 'What is the typical orbital altitude of the International Space Station?', options: ['150 km', '400 km', '1,000 km', '36,000 km'], answerIndex: 1, explanation: 'The ISS orbits around 400 kilometers high, traveling at roughly 27,600 km/h.', category: 'normal' },
  { id: 38, question: 'In theoretical physics, what is a white hole?', options: ['An active neutron star with a silicon core', 'A cooling remnants of a massive yellow dwarf', 'A theoretical time-reversed black hole that only ejects matter', 'A pocket of pure baryonic light inside dark energy voids'], answerIndex: 2, explanation: 'White holes are mathematical twins of black holes, letting matter and light exit but not enter.', category: 'normal' },
  { id: 39, question: 'What is the theoretical principle of the Alcubierre Warp Drive?', options: ['Compressing the local coordinate speed of atoms inside spacecraft engines', 'Bending space, contracting it ahead of the ship and expanding it behind', 'Triggering quantum entanglement pairs across destinations to teleport', 'Exciting dark matter filaments to create gravity slingshots'], answerIndex: 1, explanation: 'It contracts space ahead and expands it behind to travel faster than light without violating relativity.', category: 'normal' },
  { id: 40, question: 'What causes planetary auroras like the Northern Lights?', options: ['Liquid nitrogen streams reflecting lunar white light', 'Solar wind charged particles colliding with magnetosphere gas', 'Atmospheric greenhouse gases warming under solar friction', 'Ice crystal halos scattering light in troposphere layers'], answerIndex: 1, explanation: 'Charged particles from the sun strike atmospheric atoms, releasing glowing lines of visible light.', category: 'normal' },
  { id: 41, question: 'What is the "Great Attractor"?', options: ['A supergiant black hole in the Milky Way center', 'A gravitational anomaly pulling galaxies toward a colossal cluster region', 'An asteroid belt capturing rogue moons systematically', 'The initial singularity state from cyclic inflation'], answerIndex: 1, explanation: 'An immense mass anomaly in intergalactic space pulling of galaxies toward its position.', category: 'normal' },
  { id: 42, question: 'Which major galaxy is destined to merge with ours in 4.5 billion years?', options: ['Triangulum Galaxy', 'Centaurus A', 'Andromeda Galaxy', 'Sombrero Galaxy'], answerIndex: 2, explanation: 'Andromeda (M31) is heading toward us, and will merge to form Milkdromeda.', category: 'normal' },
  { id: 43, question: 'What does a "stellar nursery" refer to?', options: ['A region of high density black hole singularity fields', 'A giant dust and gas cloud (nebula) where new stars are born', 'A planetary ring collecting young cooling planetesimal chunks', 'An orbital tracking station mapping solar wind orbits'], answerIndex: 1, explanation: 'A nebula (like Orion) where gas folds together under gravity, forming protostars.', category: 'normal' },
  { id: 44, question: 'What question does the famous Fermi Paradox ask?', options: ['Why does time dilute near massive black holes?', 'How long do dark matter filaments expand?', 'If alien life is highly probable, where is everyone?', 'Why do strings vibrate in 11 dimensions?'], answerIndex: 2, explanation: 'The Fermi Paradox notes the contradiction between cosmic high probability of alien civilizations and zero detection.', category: 'normal' },
  { id: 45, question: 'What is cosmological nucleosynthesis?', options: ['A process of black holes condensing atoms into dark state layers', 'The creation of atomic cores (like Helium) inside stars or during the early universe', 'The erosion of silicon crusts under intense planetary solar heat', 'A method of synthesizing sub-atomic virtual particles in labs'], answerIndex: 1, explanation: 'Nucleosynthesis is the chemical synthesis of protons/neutrons to build nuclei.', category: 'normal' },
  { id: 46, question: 'What does CMB stand for in astrophysics?', options: ['Centuries-old Meteorite Bombardment', 'Cosmic Microwave Background (primordial radiation)', 'Crystalline Matter Binding energy', 'Chandra Magnetar Beacon spectrum'], answerIndex: 1, explanation: 'The Cosmic Microwave Background is relic radiation dating back count to 380,000 years post-Big-Bang.', category: 'normal' },
  { id: 47, question: 'What is "spaghettification" in black hole relativity?', options: ['Hot gas clouds winding into spiral galactic arms shape', 'Atomic lattices stretching vertically under extreme gravitational force differentials', 'The creation of long tube-like wormhole structures', 'Probes spinning out of control inside a vacuum field'], answerIndex: 1, explanation: 'The extreme tidal gravity pulls the feet faster than the head, stretching anything into long spaghetti shapes.', category: 'normal' },
  { id: 48, question: 'What is a Dyson Sphere?', options: ['An magnetic compass used to navigate gravitational wave fields', 'A theoretical megastructure wrapping a star to capture its energy output', 'A clean sphere of pure dark energy pushing universe expansion', 'The atmospheric protective layer surrounding Earth'], answerIndex: 1, explanation: 'Proposed by Freeman Dyson, Type II civilizations would construct spheres around parent stars.', category: 'normal' },
  { id: 49, question: 'Which rocket was used to launch the James Webb Space Telescope?', options: ['Saturn V', 'Falcon Heavy', 'Ariane 5', 'Space Launch System (SLS)'], answerIndex: 2, explanation: 'JWST was launched on an Ariane 5 rocket from French Guiana on December 25, 2021.', category: 'normal' },
  { id: 50, question: 'What is the estimated diameter of the observable universe?', options: ['13.8 Billion Light Years', '46 Billion Light Years', '93 Billion Light Years', '350 Billion Light Years'], answerIndex: 2, explanation: 'Due to ongoing spatial expansion over 13.8B years, the current observable diameter is roughly 93 Billion Light Years.', category: 'normal' }
];
